### ISSUE TITLE
Error with Linked Icon

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#11]
Possibly related to Issue #10 

```
Saved settings to object "Stagger Animation".
Traceback (most recent call last):
  File "D:\Donovan\MAXON\plugins\c4d-prototype-converter\c4d_prototype_converter\plugin_main.py", line 895, in Command
    self.do_create()
  File "D:\Donovan\MAXON\plugins\c4d-prototype-converter\c4d_prototype_converter\plugin_main.py", line 787, in do_create
    cnv.create()
  File "D:\Donovan\MAXON\plugins\c4d-prototype-converter\c4d_prototype_converter\plugin_main.py", line 433, in create
    shutil.copy(self.icon_file, files['icon'])
NameError: global name 'shutil' is not defined
```
I ran into this when trying to convert the Python Expression tag in the attached file.

[DelayAnimationExpression.zip](https://github.com/NiklasRosenstein/c4d-prototype-converter/files/1733248/DelayAnimationExpression.zip)

**Comment by donovankeith** [comment]
This is the icon file, it was saved on my Desktop.

[Sphere.zip](https://github.com/NiklasRosenstein/c4d-prototype-converter/files/1733250/Sphere.zip)

A possible complicating factor is that I'm creating my plugin somewhere other than the default preferences location.

**Comment by NiklasRosenstein** [comment]
Yup, I forgot or accidentally removed the `shutil` import at some point.
